Test

diff --git a/.github/workflows/appsignals-e2e-eks-test.yml b/.github/workflows/appsignals-e2e-eks-test.yml
--- a/.github/workflows/appsignals-e2e-eks-test.yml
+++ b/.github/workflows/appsignals-e2e-eks-test.yml
@@ -45,16 +45,16 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Download enablement script
-        uses: actions/checkout@v4
-        with:
-          repository: aws-observability/application-signals-demo
-          ref: main
-          path: enablement-script
-          sparse-checkout: |
-            scripts/eks/appsignals/enable-app-signals.sh
-            scripts/eks/appsignals/clean-app-signals.sh
-          sparse-checkout-cone-mode: false
+#      - name: Download enablement script
+#        uses: actions/checkout@v4
+#        with:
+#          repository: aws-observability/application-signals-demo
+#          ref: main
+#          path: enablement-script
+#          sparse-checkout: |
+#            scripts/eks/appsignals/enable-app-signals.sh
+#            scripts/eks/appsignals/clean-app-signals.sh
+#          sparse-checkout-cone-mode: false
 
       - name: Remove log group deletion command
         if: always()
@@ -84,168 +84,168 @@ jobs:
           role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ secrets.E2E_TEST_ROLE_ARN }}
           aws-region: ${{ inputs.aws-region }}
 
-      # local directory to store the kubernetes config
-      - name: Create kubeconfig directory
-        run: mkdir -p ${{ github.workspace }}/.kube
-
-      - name: Set KUBECONFIG environment variable
-        run: echo KUBECONFIG="${{ github.workspace }}/.kube/config" >> $GITHUB_ENV
-
-      - name: Set up kubeconfig
-        run: aws eks update-kubeconfig --name ${{ inputs.test-cluster-name }} --region ${{ inputs.aws-region }}
-
-      - name: Install eksctl
-        run: |
-          source ${{ env.TEST_RESOURCES_FOLDER }}/.github/workflows/util/execute_and_retry.sh
-          mkdir ${{ github.workspace }}/eksctl
-          curl -sLO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
-          execute_and_retry 2 "tar -xzf eksctl_Linux_amd64.tar.gz -C ${{ github.workspace }}/eksctl && rm eksctl_Linux_amd64.tar.gz"
-          echo "${{ github.workspace }}/eksctl" >> $GITHUB_PATH
-
-      - name: Create role for AWS access from the sample app
-        id: create_service_account
-        run: |
-          eksctl create iamserviceaccount \
-          --name service-account-${{ env.TESTING_ID }} \
-          --namespace ${{ env.SAMPLE_APP_NAMESPACE }} \
-          --cluster ${{ inputs.test-cluster-name }} \
-          --role-name eks-s3-access-${{ env.TESTING_ID }} \
-          --attach-policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess \
-          --region ${{ inputs.aws-region }} \
-          --approve
-
-      - name: Set up terraform
-        run: |
-          source ${{ env.TEST_RESOURCES_FOLDER }}/.github/workflows/util/execute_and_retry.sh
-          execute_and_retry 2 "wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg"          
-          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
-          sudo apt update && sudo apt install terraform
-
-      - name: Initiate Terraform
-        working-directory: terraform/eks
-        run: |
-          source ${{ env.TEST_RESOURCES_FOLDER }}/.github/workflows/util/execute_and_retry.sh
-          execute_and_retry 2 "terraform init && terraform validate" "rm -rf .terraform && rm -rf .terraform.lock.hcl"
-
-      - name: Deploy sample app via terraform and wait for the endpoint to come online
-        id: deploy-sample-app
-        working-directory: terraform/eks
-        run: |  
-          # Attempt to deploy the sample app on an EKS instance and wait for its endpoint to come online. 
-          # There may be occasional failures due to transitivity issues, so try up to 2 times. 
-          # deployment_failed of 0 indicates that both the terraform deployment and the endpoint are running, while 1 indicates
-          # that it failed at some point
-          retry_counter=0
-          max_retry=2
-          while [ $retry_counter -lt $max_retry ]; do
-            echo "Attempt $retry_counter"
-            deployment_failed=0
-            terraform apply -auto-approve \
-              -var="test_id=${{ env.TESTING_ID }}" \
-              -var="aws_region=${{ inputs.aws-region }}" \
-              -var="kube_directory_path=${{ github.workspace }}/.kube" \
-              -var="eks_cluster_name=${{ inputs.test-cluster-name }}" \
-              -var="eks_cluster_context_name=$(kubectl config current-context)" \
-              -var="test_namespace=${{ env.SAMPLE_APP_NAMESPACE }}" \
-              -var="service_account_aws_access=service-account-${{ env.TESTING_ID }}" \
-              -var="sample_app_image=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ secrets.APP_SIGNALS_E2E_FE_SA_IMG }}" \
-              -var="sample_remote_app_image=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ secrets.APP_SIGNALS_E2E_RE_SA_IMG }}" \
-            || deployment_failed=$?
-                    
-            if [ $deployment_failed -eq 1 ]; then
-              echo "Terraform deployment was unsuccessful. Will attempt to retry deployment."
-            fi
-
-            # If the deployment_failed is still 0, then the terraform deployment succeeded and now try to connect to the endpoint 
-            # after installing App Signals. Attempts to connect will be made for up to 10 minutes
-            if [ $deployment_failed -eq 0 ]; then
-              echo "Installing app signals to the sample app"
-              ${GITHUB_WORKSPACE}/enablement-script/scripts/eks/appsignals/enable-app-signals.sh \
-              ${{ inputs.test-cluster-name }} \
-              ${{ inputs.aws-region }} \
-              ${{ env.SAMPLE_APP_NAMESPACE }}
-          
-              kubectl delete pods --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
-              kubectl wait --for=condition=Ready pod --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
-          
-              echo "Attempting to connect to the endpoint"
-              sample_app_endpoint=http://$(terraform output sample_app_endpoint)
-              attempt_counter=0
-              max_attempts=60
-              until $(curl --output /dev/null --silent --head --fail $(echo "$sample_app_endpoint" | tr -d '"')); do
-                if [ ${attempt_counter} -eq ${max_attempts} ];then
-                  echo "Failed to connect to endpoint. Will attempt to redeploy sample app."
-                  deployment_failed=1
-                  break
-                fi
-          
-                printf '.'
-                attempt_counter=$(($attempt_counter+1))
-                sleep 10
-              done
-            fi
-          
-            # If the deployment_failed is 1 then either the terraform deployment or the endpoint connection failed, so first destroy the
-            # resources created from terraform and try again.
-            if [ $deployment_failed -eq 1 ]; then
-              echo "Cleaning up App Signal"
-              ./clean-app-signals.sh \
-              ${{ inputs.test-cluster-name }} \
-              ${{ inputs.aws-region }} \
-              ${{ env.SAMPLE_APP_NAMESPACE }}
-          
-              # Running clean-app-signal.sh removes the current cluster from the config. Update the cluster again for subsequent runs.
-              aws eks update-kubeconfig --name ${{ inputs.test-cluster-name }} --region ${{ inputs.aws-region }}
-
-              echo "Destroying terraform"
-              terraform destroy -auto-approve \
-                -var="test_id=${{ env.TESTING_ID }}" \
-                -var="aws_region=${{ inputs.aws-region }}" \
-                -var="kube_directory_path=${{ github.workspace }}/.kube" \
-                -var="eks_cluster_name=${{ inputs.test-cluster-name }}" \
-                -var="test_namespace=${{ env.SAMPLE_APP_NAMESPACE }}" \
-                -var="service_account_aws_access=service-account-${{ env.TESTING_ID }}" \
-                -var="sample_app_image=${{ env.SAMPLE_APP_IMAGE }}"
-          
-              retry_counter=$(($retry_counter+1))
-            else
-              # If deployment succeeded, then exit the loop
-              break
-            fi
-          
-            if [ $retry_counter -eq $max_retry ]; then
-              echo "Max retry reached, failed to deploy terraform and connect to the endpoint. Exiting code"
-              exit 1
-            fi
-          done
-
+#      # local directory to store the kubernetes config
+#      - name: Create kubeconfig directory
+#        run: mkdir -p ${{ github.workspace }}/.kube
+#
+#      - name: Set KUBECONFIG environment variable
+#        run: echo KUBECONFIG="${{ github.workspace }}/.kube/config" >> $GITHUB_ENV
+#
+#      - name: Set up kubeconfig
+#        run: aws eks update-kubeconfig --name ${{ inputs.test-cluster-name }} --region ${{ inputs.aws-region }}
+#
+#      - name: Install eksctl
+#        run: |
+#          source ${{ env.TEST_RESOURCES_FOLDER }}/.github/workflows/util/execute_and_retry.sh
+#          mkdir ${{ github.workspace }}/eksctl
+#          curl -sLO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
+#          execute_and_retry 2 "tar -xzf eksctl_Linux_amd64.tar.gz -C ${{ github.workspace }}/eksctl && rm eksctl_Linux_amd64.tar.gz"
+#          echo "${{ github.workspace }}/eksctl" >> $GITHUB_PATH
+#
+#      - name: Create role for AWS access from the sample app
+#        id: create_service_account
+#        run: |
+#          eksctl create iamserviceaccount \
+#          --name service-account-${{ env.TESTING_ID }} \
+#          --namespace ${{ env.SAMPLE_APP_NAMESPACE }} \
+#          --cluster ${{ inputs.test-cluster-name }} \
+#          --role-name eks-s3-access-${{ env.TESTING_ID }} \
+#          --attach-policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess \
+#          --region ${{ inputs.aws-region }} \
+#          --approve
+#
+#      - name: Set up terraform
+#        run: |
+#          source ${{ env.TEST_RESOURCES_FOLDER }}/.github/workflows/util/execute_and_retry.sh
+#          execute_and_retry 2 "wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg"
+#          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
+#          sudo apt update && sudo apt install terraform
+#
+#      - name: Initiate Terraform
+#        working-directory: terraform/eks
+#        run: |
+#          source ${{ env.TEST_RESOURCES_FOLDER }}/.github/workflows/util/execute_and_retry.sh
+#          execute_and_retry 2 "terraform init && terraform validate" "rm -rf .terraform && rm -rf .terraform.lock.hcl"
+#
+#      - name: Deploy sample app via terraform and wait for the endpoint to come online
+#        id: deploy-sample-app
+#        working-directory: terraform/eks
+#        run: |
+#          # Attempt to deploy the sample app on an EKS instance and wait for its endpoint to come online.
+#          # There may be occasional failures due to transitivity issues, so try up to 2 times.
+#          # deployment_failed of 0 indicates that both the terraform deployment and the endpoint are running, while 1 indicates
+#          # that it failed at some point
+#          retry_counter=0
+#          max_retry=2
+#          while [ $retry_counter -lt $max_retry ]; do
+#            echo "Attempt $retry_counter"
+#            deployment_failed=0
+#            terraform apply -auto-approve \
+#              -var="test_id=${{ env.TESTING_ID }}" \
+#              -var="aws_region=${{ inputs.aws-region }}" \
+#              -var="kube_directory_path=${{ github.workspace }}/.kube" \
+#              -var="eks_cluster_name=${{ inputs.test-cluster-name }}" \
+#              -var="eks_cluster_context_name=$(kubectl config current-context)" \
+#              -var="test_namespace=${{ env.SAMPLE_APP_NAMESPACE }}" \
+#              -var="service_account_aws_access=service-account-${{ env.TESTING_ID }}" \
+#              -var="sample_app_image=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ secrets.APP_SIGNALS_E2E_FE_SA_IMG }}" \
+#              -var="sample_remote_app_image=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ secrets.APP_SIGNALS_E2E_RE_SA_IMG }}" \
+#            || deployment_failed=$?
+#
+#            if [ $deployment_failed -eq 1 ]; then
+#              echo "Terraform deployment was unsuccessful. Will attempt to retry deployment."
+#            fi
+#
+#            # If the deployment_failed is still 0, then the terraform deployment succeeded and now try to connect to the endpoint
+#            # after installing App Signals. Attempts to connect will be made for up to 10 minutes
+#            if [ $deployment_failed -eq 0 ]; then
+#              echo "Installing app signals to the sample app"
+#              ${GITHUB_WORKSPACE}/enablement-script/scripts/eks/appsignals/enable-app-signals.sh \
+#              ${{ inputs.test-cluster-name }} \
+#              ${{ inputs.aws-region }} \
+#              ${{ env.SAMPLE_APP_NAMESPACE }}
+#
+#              kubectl delete pods --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
+#              kubectl wait --for=condition=Ready pod --all -n ${{ env.SAMPLE_APP_NAMESPACE }}
+#
+#              echo "Attempting to connect to the endpoint"
+#              sample_app_endpoint=http://$(terraform output sample_app_endpoint)
+#              attempt_counter=0
+#              max_attempts=60
+#              until $(curl --output /dev/null --silent --head --fail $(echo "$sample_app_endpoint" | tr -d '"')); do
+#                if [ ${attempt_counter} -eq ${max_attempts} ];then
+#                  echo "Failed to connect to endpoint. Will attempt to redeploy sample app."
+#                  deployment_failed=1
+#                  break
+#                fi
+#
+#                printf '.'
+#                attempt_counter=$(($attempt_counter+1))
+#                sleep 10
+#              done
+#            fi
+#
+#            # If the deployment_failed is 1 then either the terraform deployment or the endpoint connection failed, so first destroy the
+#            # resources created from terraform and try again.
+#            if [ $deployment_failed -eq 1 ]; then
+#              echo "Cleaning up App Signal"
+#              ./clean-app-signals.sh \
+#              ${{ inputs.test-cluster-name }} \
+#              ${{ inputs.aws-region }} \
+#              ${{ env.SAMPLE_APP_NAMESPACE }}
+#
+#              # Running clean-app-signal.sh removes the current cluster from the config. Update the cluster again for subsequent runs.
+#              aws eks update-kubeconfig --name ${{ inputs.test-cluster-name }} --region ${{ inputs.aws-region }}
+#
+#              echo "Destroying terraform"
+#              terraform destroy -auto-approve \
+#                -var="test_id=${{ env.TESTING_ID }}" \
+#                -var="aws_region=${{ inputs.aws-region }}" \
+#                -var="kube_directory_path=${{ github.workspace }}/.kube" \
+#                -var="eks_cluster_name=${{ inputs.test-cluster-name }}" \
+#                -var="test_namespace=${{ env.SAMPLE_APP_NAMESPACE }}" \
+#                -var="service_account_aws_access=service-account-${{ env.TESTING_ID }}" \
+#                -var="sample_app_image=${{ env.SAMPLE_APP_IMAGE }}"
+#
+#              retry_counter=$(($retry_counter+1))
+#            else
+#              # If deployment succeeded, then exit the loop
+#              break
+#            fi
+#
+#            if [ $retry_counter -eq $max_retry ]; then
+#              echo "Max retry reached, failed to deploy terraform and connect to the endpoint. Exiting code"
+#              exit 1
+#            fi
+#          done
+#
       - name: Get remote service pod name and IP
         run: |
-          echo "REMOTE_SERVICE_DEPLOYMENT_NAME=$(kubectl get deployments -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].metadata.name}')" >> $GITHUB_ENV
-          echo "REMOTE_SERVICE_POD_IP=$(kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --selector=app=remote-app -o jsonpath='{.items[0].status.podIP}')" >> $GITHUB_ENV
-
-      - name: Verify pod Adot image
-        run: |
-          kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --output json | \
-          jq '.items[0].status.initContainerStatuses[0].imageID'
-
-      - name: Verify pod CWAgent image
-        run: |
-          kubectl get pods -n amazon-cloudwatch --output json | \
-          jq '.items[0].status.containerStatuses[0].imageID'
-
+          echo "REMOTE_SERVICE_DEPLOYMENT_NAME=sample-r-app-deployment-eu-central-2-8166557505-1953" >> $GITHUB_ENV
+          echo "REMOTE_SERVICE_POD_IP=10.0.117.70" >> $GITHUB_ENV
+#
+#      - name: Verify pod Adot image
+#        run: |
+#          kubectl get pods -n ${{ env.SAMPLE_APP_NAMESPACE }} --output json | \
+#          jq '.items[0].status.initContainerStatuses[0].imageID'
+#
+#      - name: Verify pod CWAgent image
+#        run: |
+#          kubectl get pods -n amazon-cloudwatch --output json | \
+#          jq '.items[0].status.containerStatuses[0].imageID'
+#
       - name: Get the sample app endpoint
-        run: echo "APP_ENDPOINT=$(terraform output sample_app_endpoint)" >> $GITHUB_ENV
+        run: echo "APP_ENDPOINT=k8s-sampleap-sampleap-f9a0545a33-908949784.eu-central-2.elb.amazonaws.com" >> $GITHUB_ENV
         working-directory: terraform/eks
-
-      # This steps increases the speed of the validation by creating the telemetry data in advance
-      - name: Call all test APIs
-        continue-on-error: true
-        run: |
-          curl -S -s http://${{ env.APP_ENDPOINT }}/outgoing-http-call/
-          curl -S -s http://${{ env.APP_ENDPOINT }}/aws-sdk-call/
-          curl -S -s http://${{ env.APP_ENDPOINT }}/remote-service?ip=${{ env.REMOTE_SERVICE_POD_IP }}/
-          curl -S -s http://${{ env.APP_ENDPOINT }}/client-call/
+#
+#      # This steps increases the speed of the validation by creating the telemetry data in advance
+#      - name: Call all test APIs
+#        continue-on-error: true
+#        run: |
+#          curl -S -s http://${{ env.APP_ENDPOINT }}/outgoing-http-call/
+#          curl -S -s http://${{ env.APP_ENDPOINT }}/aws-sdk-call/
+#          curl -S -s http://${{ env.APP_ENDPOINT }}/remote-service?ip=${{ env.REMOTE_SERVICE_POD_IP }}/
+#          curl -S -s http://${{ env.APP_ENDPOINT }}/client-call/
 
       - name: Build Gradlew
         run: |
